#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter serverextension enable voila --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             jupyter-leaflet \
                             ipygany
